In [1]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Python\Python38\python.exe -m pip install --upgrade pip' command.


# Check dimension, shape(row and col, size(total number of element,and type of data in array))

In [3]:
# np. array support list 
import numpy as np 
array = np.array([1,2,3,4,5,6])
print(array)

[1 2 3 4 5 6]


In [4]:
print("Array is of type: ", type(array))

Array is of type:  <class 'numpy.ndarray'>


In [5]:
# Printing array dimensions (axes)
print("No. of dimensions: ", array.ndim)
 
# Printing shape of array rows and column 
print("Shape of array: ", array.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", array.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", array.dtype)

No. of dimensions:  1
Shape of array:  (6,)
Size of array:  6
Array stores elements of type:  int32


## Data types in numpy array

In [6]:
import numpy as np 
array = np.array([1,2,3,4,5,6], dtype= None, copy = True, order = None, subok = False, ndmin = 0)
print(array)

[1 2 3 4 5 6]


In [7]:
import numpy as np

array = np.array([1,2,3,4,5,6], dtype= complex, copy = True, order = None , subok = False, ndmin = 2 )
print(array)

[[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]]


In [8]:
# when setting pattern of  data in array :
a = [('name', 'S10'), ('height', float), ('age', int)]
b = [('kamini', 3.3, 10), ('yashwant', 1.9, 11),('nakte', 1.7, 12)]
c = np.array(b, dtype=a)
d = np.sort(c, order='height') # asending order by height
print(d)
e = np.sort(c, order=['age','name']) # asending order by height
print(e)

[(b'nakte', 1.7, 12) (b'yashwant', 1.9, 11) (b'kamini', 3.3, 10)]
[(b'kamini', 3.3, 10) (b'yashwant', 1.9, 11) (b'nakte', 1.7, 12)]


# Mathematical Operators

In [9]:
# Mathematical opertaion that support numpy
a = np.array([1, 2, 5, 3])
 
# add 1 to every element
print ("Adding 1 to every element:", a+1)
 
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
 
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
 
# square each element
print ("Squaring each element:", a**2)
 
# modify existing array that is multiply by 2
a *= 2
print ("Doubled each element of original array:", a,'\n')

print('Another Pattern is Transpose of array')
v = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('original array is : \n',v)
print('original array is : \n',v.T) # row become column and column become row

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6] 

Another Pattern is Transpose of array
original array is : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
original array is : 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


row wise and column wise operations

In [10]:
import numpy as np
 
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
 
# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
                    arr.max(axis = 1))
 
# minimum element of array
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))
 
# sum of array elements
print ("Sum of all array elements:",
                            arr.sum())
 
# cumulative sum along each row
print ("Cumulative sum along each row:\n",
                        arr.cumsum(axis = 1))


Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


Cumulative finding with respect to axis

In [11]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print('Dimension of an array : \n',arr1.ndim)
print('Cumulative is row wise: \n',arr1.cumsum(axis = 1))
print('Cumulative is col wise : \n',arr1.cumsum(axis = 0))

Dimension of an array : 
 2
Cumulative is row wise: 
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
Cumulative is col wise : 
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [12]:
# binary operatorsd in numpy
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])
 
# add arrays
print ("Array sum:\n", a + b)
 
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)
 
 

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]


# Array Attribute

In [13]:
import numpy as np 
arr = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
print(arr)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


 check the shape of array

In [14]:
arr.shape

(3, 4)

reset the shape of array

In [15]:
arr.shape = (6,2) # row and column
arr

array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5],
       [3, 4],
       [5, 6]])

Dimension

In [16]:
arr.ndim

2

In [17]:
#zero dimensional
zero = np.array(40)
print(zero)

40


In [18]:
#one dimensional
one = np.array([1, 2, 3, 4, 5])
print(one)


[1 2 3 4 5]


In [19]:
#two dimensional
two = np.array([[1, 2, 3, 4],[5,6,7,8]])
print(two)


[[1 2 3 4]
 [5 6 7 8]]


In [91]:
three = np.array([[[1,2,3,4,5],[2,3,4,5,6]],[[9,7,6,5,4],[5,4,3,2,7]],[[70,98,66,44,90],[9,4,3,2,1]]])
print(three)

[[[ 1  2  3  4  5]
  [ 2  3  4  5  6]]

 [[ 9  7  6  5  4]
  [ 5  4  3  2  7]]

 [[70 98 66 44 90]
  [ 9  4  3  2  1]]]


In [92]:
print(three.ndim)

3


In [20]:
#three dimensional
three = np.array([[[1, 2, 3, 4],[5,6,7,8],[2,4,8,10]]])
print(three)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 2  4  8 10]]]


In [21]:
# checking number of dimension:
print(one.ndim)
print(two.ndim)
print(three.ndim)

1
2
3


In [96]:
four = np.array(
    [
        [
            [[1, 2, 3, 4],[5,6,7,8],[2,4,8,10]]
        ],
        [
            [[1, 2, 3, 4],[5,6,7,8],[2,4,8,10]]
        ]
    ]
)

print(four)
print(four.ndim)

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 2  4  8 10]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 2  4  8 10]]]]
4


In [22]:
# creating higher dimension within array 
five = np.array([[1, 2, 3, 4],[4,5,7,8],[3,4,5,6],[7,2,7,3]], ndmin=6)
print(five)
print('number of dimensions :', five.ndim)

[[[[[[1 2 3 4]
     [4 5 7 8]
     [3 4 5 6]
     [7 2 7 3]]]]]]
number of dimensions : 6


reshape

In [23]:
five = np.array([[1, 2, 3, 4],[4,5,7,8],[3,4,5,6],[7,2,7,3]])
print(five.reshape(4,4,1))
print(five.reshape(2,4,2)) #row*col*dimension should = no of element in array

[[[1]
  [2]
  [3]
  [4]]

 [[4]
  [5]
  [7]
  [8]]

 [[3]
  [4]
  [5]
  [6]]

 [[7]
  [2]
  [7]
  [3]]]
[[[1 2]
  [3 4]
  [4 5]
  [7 8]]

 [[3 4]
  [5 6]
  [7 2]
  [7 3]]]


itemsize

In [24]:
print(five.itemsize)

4


flags:

In [25]:
print(three.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



# Array creation

1. numpy.empty

In [57]:
#numpy.empty(shape, dtype = float, order = 'C')
#Order'C' for C-style row-major array, 'F' for FORTRAN style column-major array

In [61]:
import numpy as np 
v = np.empty([3,2], dtype=int,order ='F')
print(v)

[[1310069616          0]
 [       406          1]
 [         0 1701999215]]


In [62]:
import numpy as np 
t = np.empty([3,2], dtype=int,order ='F')
print(t)

[[ 1310069616           0]
 [        406           1]
 [          0 -2147483648]]


In [35]:
import numpy as np 
x= np.empty([3,2], dtype=float,order = 'C')
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


2. np.zeros

In [40]:
y = np.zeros([3,2], dtype =int)
print(y)

[[0 0]
 [0 0]
 [0 0]]


In [41]:
y = np.zeros([3,2], dtype =float)
print(y)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [42]:
y = np.zeros([3,2], dtype =complex)
print(y)

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


In [45]:
y = np.zeros([3,2], dtype ='uint16')
print(y)

[[0 0]
 [0 0]
 [0 0]]


In [47]:
y = np.zeros(5, dtype =int)
print(y)

[0 0 0 0 0]


 3. np.ones

In [48]:
z = np.ones(5, dtype =int)
print(z)

[1 1 1 1 1]


In [50]:
import numpy as np 
x = np.ones([2,2], dtype = int) 
print (x)

[[1 1]
 [1 1]]


In [63]:
# no any other for higher numbers 

In [67]:
#array from list
import numpy as np 
x = [1,2,3,4]
y = np.array(x, dtype=int)
print(y)

[1 2 3 4]


In [72]:
#array from tuple
import numpy as np 
x = (1,2,3,4)
y = np.array(x, dtype=float)
print(y)
z = np.array(x, dtype=complex)
print(z)

[1. 2. 3. 4.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [79]:
# array from tupule in list 
x = [(1,2,3,4,5),(6,7,8,9)]
y = np.array(x)
print(y)

[(1, 2, 3, 4, 5) (6, 7, 8, 9)]


C:\Users\KAMINI\AppData\Local\Temp/ipykernel_28084/1932978848.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  y = np.array(x)


In [97]:
x = np.arange(3)
print(x)

[0 1 2]


In [100]:
# setting data type
y = np.arange(10, dtype = float)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [101]:
# start stop and step parameter 
y = np.arange(10,21,2)
print(y)

[10 12 14 16 18 20]


# array indexing and slicing 

In [110]:
one = np.array([1,2,3,4,5,6])
print(one)
print(one.ndim)

[1 2 3 4 5 6]
1


In [117]:
two = np.array([[1,2,3],[6,7,8]])
print(two)
print(two.ndim)

[[1 2 3]
 [6 7 8]]
2


In [122]:
three = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])
print(three)
print(three.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
3


In [127]:
four = np.array([[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]],[[10,20,30,40],[91,92,93,94]]]])
print(four)
print(four.ndim)

[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]

  [[10 20 30 40]
   [91 92 93 94]]]]
4


In [130]:
print(one[1])
print(two[1])
print(three[1])


2
[6 7 8]
[[ 9 10 11 12]
 [13 14 15 16]]


In [131]:
two 

array([[1, 2, 3],
       [6, 7, 8]])

In [132]:
two[0,1] # zero is row and 1 is element 

2

In [134]:
three

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [135]:
print(three[2,0,2])

19


In [136]:
four

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24]],

        [[10, 20, 30, 40],
         [91, 92, 93, 94]]]])

In [144]:
# 23 from 4 dimensional
#four[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [145]:
# reversing
one[::-1]

array([6, 5, 4, 3, 2, 1])

In [148]:
one[1:5] # start and stop

array([2, 3, 4, 5])

In [157]:
two[0,::-1]

array([3, 2, 1])

In [151]:
two

array([[1, 2, 3],
       [6, 7, 8]])

In [161]:
two[1,1]

7

In [155]:
two[1,0:3:2] # 1 index use comma then other parameters

array([6, 8])

In [158]:
three

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [159]:
three[2,1,0:3:2] # 2 index 1 2nd row then parametrs

array([21, 23])

In [160]:
three[2,1,::-1]

array([24, 23, 22, 21])

In [163]:
one

array([1, 2, 3, 4, 5, 6])

In [162]:
# add the element by passing the indexing parameters 
print(one[2] + one[3])

7


In [167]:
 import numpy as np 
a = np.arange(10) 
print (a[2::2])

[2 4 6 8]


# Numpy broadcasting:

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes 
during arithmetic operations

In [169]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
c = a*b
print('Addition of two array : ',c)

Adiition of two array :  [ 1  4  9 16 25 36 49 64 81]


In [174]:
a = np.array([[1,2,3,4,5,6,7,8,9],[0,0,0,0,0,0,0,0,0],[1,2,2,2,2,2,2,2,2]])
b = np.array([10])
c = a*b
print('Addition of two array :   \n', c)

Addition of two array :   
 [[10 20 30 40 50 60 70 80 90]
 [ 0  0  0  0  0  0  0  0  0]
 [10 20 20 20 20 20 20 20 20]]


In [178]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array: ')
print (a) 
print ('\n')  
   
print ('Second array:')
print (b)
print ('\n')   
   
print ('First Array + Second Array' )
print (a + b)

First array: 
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# numpy copy :

In [181]:
list1 = [1,2,3,4,5]
list2 = list1
print("Original : ",list2)
list1[0]=100
print("Edited : ",list1)
print("Checking for list 2 :",list2)

Original :  [1, 2, 3, 4, 5]
Edited :  [100, 2, 3, 4, 5]
Checking for list 2 : [100, 2, 3, 4, 5]
